### ISSUE TITLE
React

### ISSUE THREAD

**Issue by bak45247** [bak45247/bak45247.github.io#4]
I need to learn React.js in order to design the front end

**Comment by bak45247** [comment]
[This](https://reactjs.org/) is the react website, probably a good place to start for learning

**Comment by pradnyesh45** [comment]
Also, there are various video lectures available on youtube. As a beginner, you may refer to Codevolution.

**Comment by bak45247** [comment]
@pradnyesh45 thank you! I'll look into that once I get here

**Comment by bak45247** [comment]
[This is the codevolution react for beginners tutorial playlist](https://youtube.com/playlist?list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3)
